FROM alpine:latest

RUN apk update && apk add --no-cache nginx

RUN adduser -D -g 'nginx' mad_anoke_nginx

RUN mkdir -p /run/nginx && \
    mkdir -p /usr/share/nginx/html && \
    chown -R mad_anoke_nginx:nginx /var/lib/nginx /var/log/nginx /run/nginx /usr/share/nginx && \
    mkdir -p /var/www/html && chown -R mad_anoke_nginx:nginx /var/www/html

COPY nginx.conf /etc/nginx/nginx.conf

USER mad_anoke_nginx

CMD ["nginx", "-g", "daemon off;"]
