version: '3.8'

services:
  web:
    build: .
    volumes:
      - app_data:/app/static
      - ./config.py:/app/config.py:ro
    environment:
      - APP_CONFIG=/app/config.py
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_data:
  db_data:
