services:
  app:
    build: ./express-postgres-starter
    container_name: express-postgres-app
    environment:
      - DATABASE_URL=postgres://express_user:express_password@postgres:5432/express
      - PORT=3000
    volumes:
      - ./express-postgres-starter/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    user: "node"

  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: express
      POSTGRES_USER: express_user
      POSTGRES_PASSWORD: express_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
