# Используем легковесный образ Alpine
FROM python:3.9-alpine

# Устанавливаем зависимости
RUN apk add --no-cache gcc musl-dev postgresql-dev

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY app/requirements.txt .

# Устанавливаем зависимости Python
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY app/ .

# Очищаем кэш после установки зависимостей
RUN rm -rf /var/cache/apk/*

# Устанавливаем переменную окружения для Flask
ENV FLASK_APP=__init__.py

# Создаем непривилегированного пользователя
RUN adduser -D myuser
USER myuser

# Запускаем приложение
CMD ["flask", "run", "--host=0.0.0.0"]
